<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../samples/Textalonia.Demo/Textalonia.Demo.csproj" />
    <ProjectReference Include="../../src/Textalonia/Textalonia.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
    <PackageReference Include="Avalonia.Headless" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Fixtures/**/*.json;Fixtures/**/*.txt;Fixtures/**/*.html;Fixtures/**/*.rtf;Fixtures/**/*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
